import Link from "next/link";
import Image from "next/image";
import { PageHero } from "@/components/page-hero";
import { Container, SectionLabel, LinkArrow, JsonLd } from "@/components/ui/primitives";
import { FinalCta } from "@/components/sections/final-cta";
import { publishedProjects } from "@/data/projects";
import { pageMetadata, breadcrumbs } from "@/lib/seo";

export const metadata = pageMetadata("Réalisations et approche projet", "Découvrez comment SEYA LABS documente ses projets : contexte métier, choix de conception, solution, exploitation et enseignements.", "/realisations", publishedProjects.length === 0);
export default function Realisations() { return <><PageHero title="Chaque système a son contexte." description="Un projet ne se résume pas à une interface ou à une liste de technologies. Nous documentons le besoin, les décisions et ce que le système permet dans son contexte réel." label="RÉALISATIONS" breadcrumb={[{ name: "Réalisations" }]} /><section className="section"><Container>{publishedProjects.length ? <div className="project-grid">{publishedProjects.map((project) => <Link key={project.slug} className="project-card" href={`/realisations/${project.slug}`}><span className="mono">{project.category} / {project.client}</span><h2>{project.title}</h2><p>{project.description}</p>{project.image && <Image {...project.image} alt={project.image.alt} sizes="(max-width: 767px) 100vw, 50vw" />}</Link>)}</div> : <><div className="editorial-grid"><div><SectionLabel>CE QUE NOUS DOCUMENTONS</SectionLabel><h2>Du besoin<br />à l’usage réel.</h2></div><div><p>Le contexte : les personnes, les outils existants et les contraintes qui définissent le besoin.</p><p>La construction : les choix d’architecture, les parcours, les intégrations et les arbitrages.</p><p>La production : les usages observés, les conditions d’exploitation et les enseignements, lorsqu’ils peuvent être rendus publics.</p></div></div><div className="empty-work"><SectionLabel>PUBLICATIONS À VENIR</SectionLabel><p>Les cas projets seront ajoutés avec des informations vérifiées et l’autorisation des personnes concernées. Vous souhaitez discuter d’un besoin similaire au vôtre ? Commençons par votre contexte.</p><LinkArrow href="/contact">Parler de votre projet</LinkArrow></div></>}</Container></section><FinalCta /><JsonLd data={breadcrumbs([{ name: "Réalisations", path: "/realisations" }])} /></>; }
